server:
  port: 8080



injector:
  api:
    path: '/camel'
  kernel:
    # A list of domain objects managed by the
    domaincovidcaseid: "covidcase"
    domaincovidweeklycaseid: "covidcaseweekly"
    domaincovidfinancialpolicyid: "covidfinancialpolicy"

    schemaregistrybean: 'sandboxRegistry'
    schemaregistryindex: 'clb-hexapp-avroschema'
  staging:
    source: 'staging/inbound/source'
    deadletter: 'staging/inbound/dead.letter'
    target: 'staging/inbound/split'
    splitsize: 10000
  persistency:
    user:
      portadapter: 'userPersistencyAdapter'
      index: 'clb-hexapp-user'
    covid:
      # valid values: covidElasticSearchRouter,covidSandboxRouter
      portadapterbean: 'covidElasticSearchRouter'
      indexcovid: 'clb-hexapp-covid'
      indexcovidweekly: 'clb-hexapp-covidweekly'
      indexcovidfinpolresp:   'clb-hexapp-covidfinpolresp'
  persistence:
      elasticsearch:  # Will work with a default single node ES cluster (unprotected)
        esurl: 'http://cloudburo1:9200'
        hostaddress: 'cloudburo1:9200'
        username: ''
        password: ''

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s