/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.cloudburo.hexagon.demo.domain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Activity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3158622470193501011L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Activity\",\"namespace\":\"net.cloudburo.hexagon.demo.domain\",\"fields\":[{\"name\":\"descr\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"textual natural language description - maximal 255 characters\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Activity> ENCODER =
      new BinaryMessageEncoder<Activity>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Activity> DECODER =
      new BinaryMessageDecoder<Activity>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Activity> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Activity> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Activity>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Activity to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Activity from a ByteBuffer. */
  public static Activity fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** textual natural language description - maximal 255 characters */
   private java.lang.String descr;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Activity() {}

  /**
   * All-args constructor.
   * @param descr textual natural language description - maximal 255 characters
   */
  public Activity(java.lang.String descr) {
    this.descr = descr;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return descr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: descr = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'descr' field.
   * @return textual natural language description - maximal 255 characters
   */
  public java.lang.String getDescr() {
    return descr;
  }


  /**
   * Creates a new Activity RecordBuilder.
   * @return A new Activity RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Activity.Builder newBuilder() {
    return new net.cloudburo.hexagon.demo.domain.Activity.Builder();
  }

  /**
   * Creates a new Activity RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Activity RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Activity.Builder newBuilder(net.cloudburo.hexagon.demo.domain.Activity.Builder other) {
    return new net.cloudburo.hexagon.demo.domain.Activity.Builder(other);
  }

  /**
   * Creates a new Activity RecordBuilder by copying an existing Activity instance.
   * @param other The existing instance to copy.
   * @return A new Activity RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Activity.Builder newBuilder(net.cloudburo.hexagon.demo.domain.Activity other) {
    return new net.cloudburo.hexagon.demo.domain.Activity.Builder(other);
  }

  /**
   * RecordBuilder for Activity instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Activity>
    implements org.apache.avro.data.RecordBuilder<Activity> {

    /** textual natural language description - maximal 255 characters */
    private java.lang.String descr;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.cloudburo.hexagon.demo.domain.Activity.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.descr)) {
        this.descr = data().deepCopy(fields()[0].schema(), other.descr);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Activity instance
     * @param other The existing instance to copy.
     */
    private Builder(net.cloudburo.hexagon.demo.domain.Activity other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.descr)) {
        this.descr = data().deepCopy(fields()[0].schema(), other.descr);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'descr' field.
      * textual natural language description - maximal 255 characters
      * @return The value.
      */
    public java.lang.String getDescr() {
      return descr;
    }

    /**
      * Sets the value of the 'descr' field.
      * textual natural language description - maximal 255 characters
      * @param value The value of 'descr'.
      * @return This builder.
      */
    public net.cloudburo.hexagon.demo.domain.Activity.Builder setDescr(java.lang.String value) {
      validate(fields()[0], value);
      this.descr = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'descr' field has been set.
      * textual natural language description - maximal 255 characters
      * @return True if the 'descr' field has been set, false otherwise.
      */
    public boolean hasDescr() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'descr' field.
      * textual natural language description - maximal 255 characters
      * @return This builder.
      */
    public net.cloudburo.hexagon.demo.domain.Activity.Builder clearDescr() {
      descr = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Activity build() {
      try {
        Activity record = new Activity();
        record.descr = fieldSetFlags()[0] ? this.descr : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Activity>
    WRITER$ = (org.apache.avro.io.DatumWriter<Activity>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Activity>
    READER$ = (org.apache.avro.io.DatumReader<Activity>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
