/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.cloudburo.hexagon.demo.domain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sustainability extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5825069907109357515L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sustainability\",\"namespace\":\"net.cloudburo.hexagon.demo.domain\",\"fields\":[{\"name\":\"string\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"textual natural language description - maximal 255 characters\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sustainability> ENCODER =
      new BinaryMessageEncoder<Sustainability>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sustainability> DECODER =
      new BinaryMessageDecoder<Sustainability>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sustainability> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sustainability> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sustainability>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sustainability to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sustainability from a ByteBuffer. */
  public static Sustainability fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** textual natural language description - maximal 255 characters */
   private java.lang.String string;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sustainability() {}

  /**
   * All-args constructor.
   * @param string textual natural language description - maximal 255 characters
   */
  public Sustainability(java.lang.String string) {
    this.string = string;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return string;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: string = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'string' field.
   * @return textual natural language description - maximal 255 characters
   */
  public java.lang.String getString() {
    return string;
  }


  /**
   * Creates a new Sustainability RecordBuilder.
   * @return A new Sustainability RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Sustainability.Builder newBuilder() {
    return new net.cloudburo.hexagon.demo.domain.Sustainability.Builder();
  }

  /**
   * Creates a new Sustainability RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sustainability RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Sustainability.Builder newBuilder(net.cloudburo.hexagon.demo.domain.Sustainability.Builder other) {
    return new net.cloudburo.hexagon.demo.domain.Sustainability.Builder(other);
  }

  /**
   * Creates a new Sustainability RecordBuilder by copying an existing Sustainability instance.
   * @param other The existing instance to copy.
   * @return A new Sustainability RecordBuilder
   */
  public static net.cloudburo.hexagon.demo.domain.Sustainability.Builder newBuilder(net.cloudburo.hexagon.demo.domain.Sustainability other) {
    return new net.cloudburo.hexagon.demo.domain.Sustainability.Builder(other);
  }

  /**
   * RecordBuilder for Sustainability instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sustainability>
    implements org.apache.avro.data.RecordBuilder<Sustainability> {

    /** textual natural language description - maximal 255 characters */
    private java.lang.String string;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.cloudburo.hexagon.demo.domain.Sustainability.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.string)) {
        this.string = data().deepCopy(fields()[0].schema(), other.string);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sustainability instance
     * @param other The existing instance to copy.
     */
    private Builder(net.cloudburo.hexagon.demo.domain.Sustainability other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.string)) {
        this.string = data().deepCopy(fields()[0].schema(), other.string);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'string' field.
      * textual natural language description - maximal 255 characters
      * @return The value.
      */
    public java.lang.String getString() {
      return string;
    }

    /**
      * Sets the value of the 'string' field.
      * textual natural language description - maximal 255 characters
      * @param value The value of 'string'.
      * @return This builder.
      */
    public net.cloudburo.hexagon.demo.domain.Sustainability.Builder setString(java.lang.String value) {
      validate(fields()[0], value);
      this.string = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'string' field has been set.
      * textual natural language description - maximal 255 characters
      * @return True if the 'string' field has been set, false otherwise.
      */
    public boolean hasString() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'string' field.
      * textual natural language description - maximal 255 characters
      * @return This builder.
      */
    public net.cloudburo.hexagon.demo.domain.Sustainability.Builder clearString() {
      string = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sustainability build() {
      try {
        Sustainability record = new Sustainability();
        record.string = fieldSetFlags()[0] ? this.string : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sustainability>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sustainability>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sustainability>
    READER$ = (org.apache.avro.io.DatumReader<Sustainability>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
